version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: planradardb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
  
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      command: redis-server
      volumes:
        - 'redis:/data'

  sidekiq:
      build: .
      command: bundle exec sidekiq
      depends_on:
        - db
        - redis
      volumes:
        - .:/app
      environment:
        DATABASE_URL: postgres://root:root@db:5432/planradardb
        REDIS_URL: 'redis://redis:6379/1'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://root:root@db:5432/planradardb
      REDIS_URL: 'redis://redis:6379/1'

volumes:
  pgdata:
  redis:

